
# This is the docker version, not your project version
version: "3.7"

networks:
  carvedrock_net:
    driver: bridge

services:
  client:
    # build: "./ClientApp"
    image: honestcomrade/dotnet-gql_client
    ports: 
      - "3001:4000"
    networks:
      - carvedrock_net
  api:
    # build: "./CarvedRock.Api"
    image: honestcomrade/dotnet-gql_api
    ports: 
      - "5050:5050"
    networks:
      - carvedrock_net